### ISSUE TITLE
`Unhandled Rejection` Error in Production Run (`npm run forever`)?

### ISSUE THREAD

**Issue by traverseAI** [cozyazure/leaflet-overlay#6]
```
Unhandled rejection error: database "leafletimagedb" does not exist
    at Connection.parseE (c:\t\cozyazure\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (c:\t\cozyazure\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (c:\t\cozyazure\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:536:20)

```

**Comment by cozyazure** [comment]
Hey @traverseAI for this one, I am yet to create a database in Heroku. Is this urgent? If yes then I will do it later. Don't really have free Postgres hosting, the ones that is are limited and low performance.

**Comment by traverseAI** [comment]
Oh I saw the "amazon EC2" wording in prod db and thought it was working!
No, not urgent for today. I am just trying out commenting and discussing on
github issues with you :D

Thet

**Comment by cozyazure** [comment]
Aha okay. Will fix it up soon. Just a note, storing image in Postgres default database is not the ideal way, am just trying to get the MVP up so this hacky move (lazy to set up :P) . In real word case scenario, will have to move to blob storage or something for storing large file images. Either we move to Azure Blob Storage, or Postgres itself have blob storage but need additional set up.

**Comment by traverseAI** [comment]
Yes thats correct. For binary files (picture or not), we can also put on
AWS S3 and store the S3 location URL in the db column.

Thet

**Comment by cozyazure** [comment]
Okay we will explore the options when we reached that stage.
